### ISSUE TITLE
Decide on Project Subject

### ISSUE THREAD

**Issue by MihaiVladS** [opgeROBt/dPrep-Team-8-investigating-airbnb#4]
With Air B&B Data decide:
- What to analyze
- Motivation as to why we analyze that

**Comment by opgeROBt** [comment]
idea: price prediction of a listing

**Comment by MihaiVladS** [comment]
I thought of an idea: 

We could combine all of the listing files from capital cities specifically. In that case we would have to make sure that each individual listings.csv file has an added column with the capital city before merging, because there's nothing in the files to indicate that except for the neighborhood and coordinate digits. Once we merge them, we could have as dependent variable reviews_per_month and room_type as independent. This alone can tell us if the type of room offered affects the rate at which people review. However, we can use neighborhoods as a moderator and see how location influences this effect. On top of that, we can also add capital cities to see the overall performance of this relationship per city. 

As for motivation, I'm thinking of the following:

This can be useful information for the average bnb hoster - since reviews are important and determine what places are shown to you first. This can tell you what expectations you should have review-wise based on the type of room you host. If you're looking to purchase a place that you might rent out frequently, this can tell you if you should look for an apartment or house. Neighborhood and/or capital city can also be useful to the same effect, how would your place perform based on location and where should you purchase a room if you want to host it on bnb,

This can also be useful for bnb managers - they may find that some locations have disadvantages review-wise and may want to include a way to motivate users to review their hosts.

**Comment by chokietang** [comment]
**Research question AirBnb**
Is the charging price of the neighbourhood Amsterdam Centrum-Oost and Amsterdam Centrum-West higher compared to the other neighbourhoods in Amsterdam?
or
What is the difference in charging price on average between the rentals located in the centrum of Amsterdam (Centrum-Oost and Centrum-West) and the other neighboorhoods in Amsterdam?

A lot of tourists visit Amsterdam and I think a lot of them prefer to rent an AirBnb located in the centrum of Amsterdam, because of the sightseeings. So I thought, maybe the hosts of the AirBnb's in the centrum of Amsterdam charge a higher price compared to the hosts of the AirBnb's that are not located in the centrum, because of the location?

**Comment by Cas-24** [comment]
What is the effect of price (IV) on review_scores_value (DV) between different European Capitals? And to what extent does this relationship depend on if there where COVID-19 restrictions or not. COVID-19 restrictions are a moderating variable (quasi moderator).

What is the effect of room_type (IV) on the review_scores_rating (DV) between different European Capitals? And to what extent does this relationship depend on the average nights stayed.

What is the effect of room_type (IV) on the review_scores_rating (DV) between different European Capitals? And to what extent does this relationship depend on having a Superhost or not?

**Comment by Anoesjka97** [comment]
What is the effect of neighborhood (IV) on the review_scores_rating (DV)

maybe this and then in different cities?
